### ISSUE TITLE
本地帐号支持第三方应用授权码登录

### ISSUE THREAD

**Issue by wuyongCloud** [bestaone/HiAuth#3]
一般都是使用第三方帐号登录项目，有没有在第三方系统登录支持本地帐号Oauth2 授权码模式，

**Comment by bestaone** [comment]
Oauth2本身就是一个“开放的授权标准”，这里实现了这个标准。现在许多第三方也是实现Oauth2授权标准的。所以本项目和你所指的第三方系统，从功能上面是平级的，没有互相集成的说法。
